config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users #, :only => [:new, :create, :index, :show, :edit, :delete]
  resources :posts #, :only => [:new, :create, :index, :show, :edit, :delete]
  resources :pages

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base 
 belongs_to :post
 belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base 
    belongs_to :user, :optional => true
end

app/models/user.rb
class User < ActiveRecord::Base 
    validates :email, :presence => true, :uniqueness => true
    has_secure_password
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
  
    private
    def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present?
    end
  
    def check_for_login
      redirect_to login_path unless @current_user.present?
    end
  
    def check_for_admin
      redirect_to root_path unless (@current_user.present? && @current_user.admin?)
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all.sort_by {|comment| comment.created_at}.reverse!
  end

  def show
    @comment = Comment.find params[:id]
  end

  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create comment_params
    redirect_to comment
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def update
    comment = Comment.find params[:id]
    comment.update comment_params
    redirect_to comment
  end

  def destroy
    comment = Comment.find params[:id]
    comment.destroy
    redirect_to comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:created_at, :updated_at)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_for_login

  def home    
    @posts = Post.order(created_at: :desc)
    @users = User.where.not(id: @current_user.id).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_for_login

  def index
    @posts = Post.all.sort_by {|post| post.created_at}.reverse!
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new post_params
    if params[:post][:photo].present?
      req = Cloudinary::Uploader.upload(params[:post][:photo])
      post.photo = req["public_id"]
      post.user_id = @current_user.id
      post.save 
    end
    redirect_to post_path(post)
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    post = Post.find params[:id]
    if params[:post][:photo].present?
      req = Cloudinary::Uploader.upload(params[:post][:photo])
      phost.photo = req["public_id"]
    end    
    post.update_attributes post_params
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find params[:id]
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:photo, :location, :description, :comment_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by :email => params[:email]
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        redirect_to login_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to login_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, except: [:new, :create]
  
  def new
    @user = User.new
  end

  def index
    check_for_admin
    @users = User.all
  end

  def show
      @user = User.find params[:id]
      @is_current_user = @user.id == @current_user.id
  end

  def delete
    if @current_user.admin?
      @user = User.find params[:id]
    else
      @user = @current_user
    end
    redirect_to root_path
  end
  
  def edit
    if @current_user.admin?
      @user = User.find params[:id]
    else
      @user = @current_user
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    user = User.find params[:id]
    user.update_attributes user_params
    redirect_to user
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :avatar, :dob, :bio, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<h1>All Comments</h1>

<% @comments.each do |comment|  %>
   <%= comment.comment %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<h1>edit comment</h1>

<%= comment.comment %>

<div class="controls">
  <%= link_to 'Edit comment', edit_comment_path(@comment) %>
  <%= link_to 'Delete comment', @comment, :method => 'delete', :class => 'bananas', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pho Mo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= cloudinary_js_config %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;500;600;700&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <link rel="icon" type="image/png" href="./assets/favicon-16x16.png" />
  </head>

  <body>
  <% if @current_user.present? %>
  <header>
      <div id="logo">
        <a href="/"
          ><img src="/assets/phomo-black-text172.png" id="header-logo" />
        </a>
      </div>
      <div id="search">
        <div class="box">
          <div class="search-input">
            <span class="icon"><i class="fa fa-search"></i></span>
            <input type="search" id="search" placeholder="Search" />
          </div>
        </div>
      </div>
      <nav id="top-nav">
        <%= link_to root_path, :class => 'nav-a' do %>
          <i class="fas fa-home nav-icon"></i>
        <% end %>        
        <%= link_to new_post_path, :class => 'nav-a' do %>
          <i class="far fa-plus-square"></i>
        <% end %>
        </a>
        <a href="#" class="nav-a">
          <i class="far fa-compass nav-icon"></i>
          </a>
        <a href="#" class="nav-a">
          <i class="far fa-heart nav-icon"></i>
        </a>
        <% if @current_user.admin? %>
            <%= link_to users_path, :class => 'nav-a' do %>
              <i class="fas fa-users nav-icon"></i>
            <% end %>
        <% end %>
        <%= link_to @current_user, :class => 'nav-a' do %>
          <i class="far fa-user-circle nav-icon"></i>
        <% end %>
      </nav>
    </header>
    <% end %>
    <div class="container">      
      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id="central-feed">
  <div id="suggested-follows" class="suggested-follow main-box">
    <% @users.each do | user | %>
      <%= link_to user do %>
        <div class="suggested-follow-profile">
          <div
            class="profile-pic-wrapper"
            style="background-image: url(<%= user.avatar if user.avatar.present? %>)"
          ></div>
          <h4><%= user.username if user.username.present? %></h4>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="news-feed">
    <% @posts.each do |post| %>
      <%= link_to post do %>
        <section class="feed-post main-box">
          <div class="post-head-user">
            <div class="post-head-user-items">
              <div
                class="post-avatar profile-pic-wrapper"
                style="background-image: url(<%= post.user.avatar if post.user.present? %>)"
              ></div>
              <h2><%= post.user.email if post.user.present? %></h2>
            </div>
            <div class="post-menu"><i class="fas fa-ellipsis-h"></i></div>
          </div>
          <div class="post-content">
            <%= cl_image_tag post.photo %>
          </div>
          <div class="post-footer">
            <div class="post-footer-actions">
              <div class="post-footer-actions-right">
                <i class="far fa-heart nav-icon"></i>
                <i class="far fa-comment-alt nav-icon"></i>
                <i class="far fa-envelope nav-icon"></i>
              </div>
              <div class="post-footer-actions-left">
                <i class="far fa-bookmark nav-icon"></i>
              </div>
            </div>
            <div class="post-likes">
              <div
                class="post-likes-avatar profile-pic-wrapper"
                style="background-image: url(./images/150.jpg)"
              ></div>
              <div class="post-likes-users">
                <p>Liked by <h2>4</h2></p>
              </div>
            </div>
            
            <div class="new-comment">
              <div class="emoji-keyboard">
                <i class="far fa-smile nav-icon"></i>
              </div>
              <div class="comment-input">
                <p>Comment</p>
              </div>
            </div>
          </div>
        </section>
      <% end %>
      <%#= link_to image_tag(post.photo, :class => 'photo'), post %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div id="central-feed">
  <%= form_for @post, :html => { :multipart => true } do |f| %>
        <section class="feed-post main-box">
          <div class="post-head-user">
            <div class="post-head-user-items">
              <h2>Edit Post</h2>
              <div
                class="post-avatar profile-pic-wrapper"
                style="background-image: url(<%#= post.user.avatar if post.user.present? %>)"
              >

              </div>
              <h2><%#= post.user.email if post.user.present? %></h2>
            </div>
            <div class="post-menu"></div>
          </div>
          <div class="post-content">
            <%#= cl_image_tag post.photo %>
              <%= f.label :description %>
              <%= f.text_field :description %>
              <%= f.label :location %>
              <%= f.text_field :location %>
          </div>
          <div class="post-footer">
            <div class="post-footer-actions">
              <%= f.label :photo %>
              <%= f.file_field :photo %>
              <div class="post-footer-actions-left">
              <%= f.submit "Create Post" %>
              </div>
            </div>

          </div>
        </section>
        <% end %>
  </div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<div class="index container">
<% @posts.each do |post| %>
  <%= link_to cl_image_tag(post.photo, :class => 'photo'), post %>
<% end %>

</div>

app/views/posts/new.html.erb
<div id="central-feed">
  <%= form_for @post, :html => { :multipart => true } do |f| %>
        <section class="feed-post main-box">
          <div class="post-head-user">
            <div class="post-head-user-items">
              <h2>Create New Post</h2>
              <div
                class="post-avatar profile-pic-wrapper"
                style="background-image: url(<%#= post.user.avatar if post.user.present? %>)"
              >

              </div>
              <h2><%#= post.user.email if post.user.present? %></h2>
            </div>
            <div class="post-menu"></div>
          </div>
          <div class="post-content">
            <%#= cl_image_tag post.photo %>
              <%= f.label :description %>
              <%= f.text_field :description %>
              <%= f.label :location %>
              <%= f.text_field :location %>
          </div>
          <div class="post-footer">
            <div class="post-footer-actions">
              <%= f.label :photo %>
              <%= f.file_field :photo %>
              <div class="post-footer-actions-left">
              <%= f.submit "Create Post" %>
              </div>
            </div>

          </div>
        </section>
        <% end %>
  </div>

app/views/posts/show.html.erb
<h1><%= @post.description %></h1>

<%= cl_image_tag @post.photo %>

<%= @post.location %>

app/views/session/new.html.erb
<div
  id="index-background"
  style="background-image: url(./assets/background.png)"
>
  <div class="login-page">
    <div>
      <img id="login-logo" src="assets/phomo-black-text172.png" />
      <div class="form-wrapper">
        
        <%= form_tag login_path do %>
          <div class="input-wrapper">            
            <%= email_field_tag :email, nil, :id => 'username', placeholder: 'Email' %>
          </div>

          <div class="input-wrapper">            
            <%= password_field_tag :password, nil, :id => 'password', placeholder: 'Password' %>
          </div>

          <%= button_tag 'Sign in', :type => 'submit', :id => 'login-button' %>
          
        <% end %>
        <div id="forgot">Forgot Password?</div>
        <div id="sign-up">
          Don't have an account? <%= link_to 'Sign up', new_user_path %>
        </div>
      </div>
    </div>
    <footer>© 2021 PhoMo by Tracey Hill</footer>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :dob, 'Date of birth' %>
  <%= f.text_field :dob, :placeholder => 'YYYY-MM-DD' %>
  <%= f.label :avatar%>
  <%= f.text_field :avatar %>
  <%= f.label :bio %>
  <%= f.text_field :bio %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render :partial => 'form' %>

app/views/users/feed.html.erb
<h1>Feed</h1>

app/views/users/index.html.erb
<h1>All Users</h1>
<div class="index container">
<% @users.each do |user| %>
 <div class="card"> 

  <%= image_tag user.avatar, :class => 'thumb' if user.avatar.present? %>

   <%= link_to user.email, user %>
  
 </div>
<% end %>

</div>

app/views/users/new.html.erb
<div
  id="index-background"
  style="background-image: url(/assets/background.png)"
>
  <div class="login-page">
    <div>
      <img id="login-logo" src="/assets/phomo-black-text172.png" />
      <div class="form-wrapper">
        
        <% if @user.errors.any? %>
          <ol>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ol>
        <% end %>

        <%= form_for @user do |f| %>
          <div class="input-wrapper">            
            <%= f.email_field :email, :id => 'username', placeholder: 'Email' %>
          </div>

          <div class="input-wrapper">            
            <%= f.password_field :password, :id => 'password', placeholder: 'Password' %>
          </div>

          <div class="input-wrapper">            
            <%= f.password_field :password_confirmation, :id => 'password', placeholder: 'Confirm Password' %>
          </div>

          <%= f.button 'Sign up', :type => 'submit', :id => 'login-button' %>
        <% end %>

        <div id="forgot2">Forgot Password?</div>
        <div id="sign-up2">
          Already have an account? <%= link_to 'Sign in', login_path %>
        </div>
      </div>
    </div>
    <footer>© 2021 PhoMo by Tracey Hill</footer>
  </div>
</div>




<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

app/views/users/show.html.erb
<div class="main-profile-header">
  <div class="main-avatar">
    <div
      class="profile-pic-wrapper main-profile-avatar"
      style="background-image: url(<%= @user.avatar if @user.avatar.present? %>)"
    ></div>
  </div>
  <div class="main-profile-info">
    <div class="top-profile">
      <h2 id="user-name"><%= @user.username if @user.username.present? %></h2>
      <% if @is_current_user %>
        <%= link_to edit_user_path(@user) do %>
          <button>Edit Profile</button>
        <% end %>
        <i class="fas fa-cog"></i>
      <% end %>
    </div>
    <div class="middle-profile">
      <p><span id="posts-number"><%= @user.posts.count %></span> posts</p>
      <p><span id="followers">0</span> followers</p>
      <p><span id="following">0</span> following</p>
    </div>
    <div class="bottom-profile">
      <p id="bio">
        <%= @user.bio if @user.bio.present? %>
      </p>
    </div>
    
      <div class="middle-profile">
        <% if @is_current_user %>
          <%= link_to login_path, :method => 'delete'  do %>
            <button>Sign out</button>
          <% end %>
        <% end %>
        <% if @current_user.admin? %>
          <% unless @is_current_user %>
            <%= link_to edit_user_path(@user) do %>
              <button>Edit Profile</button>            
            <% end %>
          <% end %>
          <%= link_to @user, :method => 'delete', :data => { :confirm => "Delete #{ @user.email } Are you sure?" } do %>
            <button>Delete Profile</button>
          <% end %>
        <% end %>
      </div>
    
  </div>
</div>
<div id="post-parent" class="main-profile-posts">
  <% @user.posts.each do |post| %>
    <div class="profile-post">
      <div class="post-content">
        <%= cl_image_tag post.photo %>
        <div class="links">
          <a href=""><i class="fa fa-heart"></i><span></span></a>
          <a href=""><i class="fa fa-comment-alt"></i><span></span></a>
        </div>
      </div>
    </div>
  <% end %>
</div>